import Conf from 'conf';
import { createTask, updateTask } from '../store/tasks.js';
import { createWorktree, formatBranchName, commitAndPush, createPR } from '../utils/git.js';
import { ClaudeService } from './claude.js';
import type { Task } from '../types.js';
import type { ProgressStage } from '../components/LoadingProgress.js';

const config = new Conf({ projectName: 'oneshot' });

export interface TaskProgress {
  stage: ProgressStage;
  message?: string;
}

export async function createAndExecuteTask(
  name: string,
  prompt: string,
  onProgress?: (progress: TaskProgress) => void
): Promise<Task> {
  const branchPrefix = (config.get('branchPrefix') as string) || 'task';
  const branchName = formatBranchName(branchPrefix, name);

  onProgress?.({ stage: 'worktree', message: `Creating worktree for branch: ${branchName}` });

  let task: Task;
  try {
    const taskId = Math.random().toString(36).substring(2, 10);
    const worktreePath = createWorktree(branchName, taskId);

    task = createTask(name, prompt, branchName, worktreePath);

    onProgress?.({ stage: 'claude_init', message: `Task #${task.number} created. Initializing Claude...` });
    updateTask(task.id, { status: 'in_progress' });

    try {
      const claude = new ClaudeService();
      let accumulatedLogs = '';

      const response = await claude.executeTaskInWorktree(
        prompt,
        worktreePath,
        (log, stage) => {
          accumulatedLogs += log;
          updateTask(task.id, { logs: accumulatedLogs });
          if (stage) {
            onProgress?.({ stage, message: log });
          }
        }
      );

      updateTask(task.id, { result: response.content, logs: accumulatedLogs });

      onProgress?.({ stage: 'committing', message: 'Committing and pushing changes...' });
      const commitMessage = `${name}\n\nGenerated by oneshot CLI`;
      commitAndPush(worktreePath, branchName, commitMessage);

      onProgress?.({ stage: 'creating_pr', message: 'Creating pull request...' });
      const prUrl = createPR(worktreePath, name, prompt);

      updateTask(task.id, { status: 'completed', prUrl });
      onProgress?.({ stage: 'completed', message: `Task #${task.number} completed! PR: ${prUrl}` });

      return task;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';

      if (errorMessage.includes('No changes to commit')) {
        updateTask(task.id, {
          status: 'needs_action',
          error: 'No changes were made. Task may need clarification or manual intervention.'
        });
      } else {
        updateTask(task.id, { status: 'failed', error: errorMessage });
      }

      throw error;
    }
  } catch (error) {
    throw error;
  }
}
