import Conf from 'conf';
import { createTask, updateTask } from '../store/tasks.js';
import { createWorktree, formatBranchName, commitAndPush, createPR } from '../utils/git.js';
import { ClaudeService } from './claude.js';
import type { Task } from '../types.js';

const config = new Conf({ projectName: 'oneshot' });

export async function createAndExecuteTask(
  name: string,
  prompt: string,
  onProgress?: (message: string) => void
): Promise<Task> {
  const branchPrefix = (config.get('branchPrefix') as string) || 'task';
  const branchName = formatBranchName(branchPrefix, name);

  onProgress?.(`Creating worktree for branch: ${branchName}...`);

  let task: Task;
  try {
    const taskId = Math.random().toString(36).substring(2, 10);
    const worktreePath = createWorktree(branchName, taskId);

    task = createTask(name, prompt, branchName, worktreePath);

    onProgress?.(`Task #${task.number} created. Executing with Claude...`);
    updateTask(task.id, { status: 'in_progress' });

    try {
      const claude = new ClaudeService();
      const response = await claude.executeTaskInWorktree(prompt, worktreePath);

      updateTask(task.id, { result: response.content });

      onProgress?.(`Committing and pushing changes...`);
      const commitMessage = `${name}\n\nGenerated by oneshot CLI`;
      commitAndPush(worktreePath, branchName, commitMessage);

      onProgress?.(`Creating pull request...`);
      const prUrl = createPR(worktreePath, name, prompt);

      updateTask(task.id, { status: 'completed', prUrl });
      onProgress?.(`✓ Task #${task.number} completed! PR: ${prUrl}`);

      return task;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';

      if (errorMessage.includes('No changes to commit')) {
        updateTask(task.id, {
          status: 'needs_action',
          error: 'No changes were made. Task may need clarification or manual intervention.'
        });
        onProgress?.(`⚠ Task #${task.number} needs action: No changes made`);
      } else {
        updateTask(task.id, { status: 'failed', error: errorMessage });
        onProgress?.(`✗ Task #${task.number} failed: ${errorMessage}`);
      }

      throw error;
    }
  } catch (error) {
    throw error;
  }
}
